# Generated by Django 4.2.10 on 2024-03-02 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_remove_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='products/main/', verbose_name='Фото'),
        ),
    ]
