# Generated by Django 4.2.10 on 2024-03-02 14:02

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_product_main_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='additional_info',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Характеристики'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
