# Generated by Django 4.2.10 on 2024-03-02 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_product_additional_info_alter_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, upload_to='category/', verbose_name='Фото'),
        ),
    ]
