# Generated by Django 4.2.10 on 2024-03-10 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_cartorder_wishlist_productreview_cartorderitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='pid',
        ),
        migrations.AlterField(
            model_name='productreview',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='product.product', verbose_name='Продукт'),
        ),
    ]
