# Generated by Django 4.2.10 on 2024-03-16 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_product_pid_alter_productreview_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='invoice_no',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='product_status',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
